project:
  type: book

book:
  title: "PyTorch Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/pytorch-notes
  site-url: https://pytorch-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Basic
      chapters:
        - contents/basic/quickstart_tutorial.ipynb
        - contents/basic/tensorqs_tutorial.ipynb
    - part: SMP
      chapters: 
        - text: SMP Library Codebase
          href: "contents/segmentation/smp-architecture-oop.qmd"
        - text: SMP Components
          href: "contents/segmentation/smp-components-explained.qmd"
    - references.qmd

format:
  html:
    theme:
      light:
      - cosmo
      dark:
      - darkly
    toc-depth: 4

execute:
  freeze: auto
  execute-dir: project

freeze: auto
